Guidelines visibility in dark mode
singodiyashubham87/Draw-it-out pull request #231
Opened 2024-05-29 16:47 UTC by 18Venus

# Issue Title:  Visibility Issue in Dark Mode
*resolve issue:* #207 

## Type of change ☑️

What sort of change have you made:
I have fixed the CSS of the guidelines box so that the text is clearly visible in both light and dark mode.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Code style update (formatting, local variables)

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

I have run the code and here are the screenshots of the changes: 

Light Mode(No change):
![light-mode](https://github.com/singodiyashubham87/Draw-it-out/assets/149051659/be5d01e3-87fa-42bd-8f04-b403e7bd29ea)

Dark Mode(changed):
![dark-mode](https://github.com/singodiyashubham87/Draw-it-out/assets/149051659/689c9eee-bcb2-4843-b9ec-c40ad8010be0)

2024-05-31 14:19 UTC, 0xabdulkhalid requested changes
Instead of `#F4CBB2` you can use `#FFFFFF`/ `#F5F5F5`.

2024-05-31 14:20 UTC, 0xabdulkhalid requested changes

2024-05-31 14:20 UTC, 0xabdulkhalid commented on tailwind.config.js
> +      },
Instead of `#F4CBB2` you can use `#FFFFFF`/ `#F5F5F5`.

2024-05-31 16:19 UTC, 0xabdulkhalid approved these changes
LGTM 👀 

Now this PR is ready to be merged! @singodiyashubham87 🚀

2024-06-02 09:52 UTC, merged

2024-06-02 09:52 UTC, singodiyashubham87 commented
@18Venus Well Done, Keep contributing :)