Prevent tour from showing if already seen
singodiyashubham87/Draw-it-out pull request #438
Opened 2024-07-03 13:31 UTC by LyubomirT

# Issue Title: [Bug]: Tutorial appears even if the website has already been accessed before.
*closes* #434

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 
## How Has This Been Tested? ⚙️

Hosted my own instance of the website and tested the new bugfix there, everything seemed to work.

2024-07-05 10:24 UTC, singodiyashubham87 commented
@LyubomirT You could have done the cookies part without using any library too, isn't it?

2024-07-05 12:13 UTC, LyubomirT commented
@singodiyashubham87 Sorry for that, I just figured it'd be more convenient for you if I used JS-Cookie, I guess it's the opposite. Changing the code to work with cookies without it.

2024-07-07 17:52 UTC, singodiyashubham87 commented on src/App.jsx
Kindly add these functions related to cookies like setCookie & getCookie inside a separate file './src/utils/manageCookies.js" & import them in "App.jsx"

2024-07-07 17:52 UTC, singodiyashubham87 requested changes
Kindly do the addressed changes.

2024-07-08 08:52 UTC, LyubomirT commented on src/App.jsx
Made changes, please review the code again and let me know if it works for you.

2024-07-08 08:53 UTC, LyubomirT commented
@singodiyashubham87 Implemented what you asked for, please review the code again and let me know if it works well.

2024-07-08 18:42 UTC, singodiyashubham87 commented
@LyubomirT Kindly resolve the conflicts.

2024-07-13 22:39 UTC, singodiyashubham87 approved these changes
Approved!

2024-07-13 22:39 UTC, merged

2024-07-13 22:40 UTC, singodiyashubham87 commented
@LyubomirT Well Done!