Add hover effect to social media icons
singodiyashubham87/Draw-it-out pull request #482
Opened 2024-07-20 16:05 UTC by TBorundia

# Issue Title: Add hover effect to social media icons
*closes* #457

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️
- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] My changes generate no new warnings.
- [X] I have added things that prove my fix is effective or that my feature works.

## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

https://github.com/user-attachments/assets/f805e9dc-5fb0-444f-b836-d92717595cf9

2024-07-20 16:06 UTC, TBorundia commented
@singodiyashubham87 Sir,
Please review this PR.
Thank You!

2024-07-22 09:30 UTC, singodiyashubham87 requested changes
Review the changes.

2024-07-22 09:30 UTC, singodiyashubham87 commented on package-lock.json
You don't have to make changes to this file.

2024-07-22 09:53 UTC, TBorundia commented
> Review the changes.

@singodiyashubham87 sir, Now I have resolved the conversation .
Please review this.

2024-07-22 10:09 UTC, singodiyashubham87 approved these changes
Approved!

2024-07-22 10:09 UTC, merged