Add title on hover
singodiyashubham87/Draw-it-out pull request #494
Opened 2024-07-26 14:39 UTC by KomalSrivastava

# Issue Title: 
Fixes issue #477 

## Type of change ☑️
I have added hover in each and the title of the tool , when the user point curser to the icon then it show the effect and the title or you can say the topic.
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

 @singodiyashubham87 Review this and merge my issue.
## How Has This Been Tested? ⚙️

Describe how have you verified the changes made.

2024-07-27 05:44 UTC, singodiyashubham87 commented on Draw-it-out
You don't have to create a submodule.

2024-07-27 05:44 UTC, singodiyashubham87 requested changes
Do the changes.

2024-07-29 10:30 UTC, singodiyashubham87 commented
@KomalSrivastava You need to remove the submodules not add them.

2024-07-29 12:57 UTC, KomalSrivastava commented
@singodiyashubham87 removed.

2024-08-01 12:35 UTC, KomalSrivastava commented
@singodiyashubham87 Can you review it!!

2024-08-01 17:55 UTC, KomalSrivastava commented
@singodiyashubham87 Review and merge it please !!

2024-08-05 12:22 UTC, KomalSrivastava commented
@0xabdulkhalid @singodiyashubham87  ??

2024-08-05 17:25 UTC, singodiyashubham87 commented
@KomalSrivastava There is still a sub-module.
You should take care of all these things before creating a PR.
![image](https://github.com/user-attachments/assets/29f2f0c6-d8ab-4558-bd16-f4d2d47b7f39)

2024-08-06 05:47 UTC, KomalSrivastava commented
@singodiyashubham87 I have removed .gitmodule may be haven't updated , my apology. now removed.

2024-08-06 06:30 UTC, closed without merging

2024-08-06 06:31 UTC, KomalSrivastava commented
@singodiyashubham87 i will create new PR . here error is showing

2024-08-06 16:24 UTC, singodiyashubham87 commented
@KomalSrivastava Go Ahead!